import blog1 from "../../assets/images/blog-1.webp";
import blog2 from "../../assets/images/women-in-the.webp";
import blog3 from "../../assets/images/blog-3.webp";
import blog5 from "../../assets/images/blog-5.webp";
import blog6 from "../../assets/images/blog-6.webp";

export const blogData = [
  {
    id: 1,
    title:
      "How industries evolve: Interactions, not institutions, drive disruptive change",
    category: "Industries",
    img: blog5,
    content:
      "We’ve all seen it happen. Our industry is humming along with business as usual, staying more or less stable for perhaps years at a time. Then something erupts onto the scene—a new technology,1 a public health crisis,2 a major geopolitical shift, even a dramatic change in fashion preferences3—that turns the industry upside down, leaving a swath of failed organizations in its wake. If we’re lucky, we avoid being disrupted, and we may even thrive in the new state of affairs. But what about the organizations that didn’t survive? Why didn’t they see the change coming? And if they did, why weren’t they able to adapt?\n  Disruption—unanticipated step changes in how an industry does business—is one of the main, certainly the most dramatic, forms of industry evolution. What’s less evident, though, is the underlying mechanism responsible for much of this evolution. Whether it’s Blockbuster falling to Netflix or Oracle’s successful transition to cloud,4 we tend to ascribe an organization’s failure or success in dealing with disruption to attributes of the organization itself. They’re too slow or too big or, conversely, unusually agile and prepared. But rarely do we dig deeper to ask: What are the Blockbusters of the world too slow at and too big for? What did Oracle do with all that agility? \n When we examine the way industries evolve, time and time again, we find that it’s the relationships among organizations—their networks and interactions—that speed disruption along or stand in its way. Streaming video disrupted Blockbuster because distributing physical products requires different institutional relationships from distributing virtual products, and the role Blockbuster played in the physical supply chain simply did not exist in the virtual one. Transitioning to streaming would have required Blockbuster to unpick the property and franchising relationships that had hitherto defined its operations while simultaneously building new relationships for virtual distribution. It’s a prime example of a company where institutional relationships that had once been a competitive advantage became an insurmountable burden.",
  },
  {
    id: 2,
    title: "Nigeria economic outlook",
    category: "Economy",
    img: blog3,
    content:
      "Nigeria Economy recovery is losing steam. GDP growth has see-sawed after a strong start in early summer last year. Over the autumn and winter months, activity was hit by disruptions in energy and labour supply, and the imposition of ‘Plan B’ restrictions in response to the omicron wave. So far this year, the inflationary effects of the war in Ukraine and lockdowns in China have added to existing price pressures, hitting consumer confidence and activity. \n High-frequency data indicates a broad-based slowdown. Consumer confidence has collapsed as people curtail purchasing, with retail sales volumes down by 7% since last April (figure 1). Recent purchasing managers indices also point to a gradual deceleration in manufacturing activity, with new export orders on the decline. \n We expect this weakness to continue into the second quarter. As the government winds up its COVID-19 testing programme, health care activity is declining. Inflation, which hit a 30-year high in March, is set to rise further, with a revision of the government’s energy price cap translating into an average 54% rise in household energy bills in April (figure 2). This, alongside tax rises that have just come into effect, will further squeeze consumer spending power. In fact, the government’s Office for Budget Responsibility reckons this fiscal year will see inflation rise to a 40-year high, resulting in the sharpest squeeze on household disposable incomes since the 1950s.",
  },
  {
    id: 3,
    title: "Weekly global economic update",
    category: "Economy",
    img: blog1,
    content:
      "The biggest risk to Europe’s economy stems from uncertainty about the flow of natural gas. A major disruption of gas in the coming winter could push Europe into recession. Last month, Gazprom, the state-run Russian gas company, reduced the flow of gas in the Nord Stream 1 pipeline by more than is usually the case for summer maintenance. It said this was done to repair a turbine made in Germany, which sent the equipment to Canada for repair work. Based on existing sanctions, there was uncertainty as to whether the turbine would be returned by Canada. However, the Canadian government noted that Germany would suffer “very significant hardship” if the pipeline is not repaired and, therefore, decided to return the turbine. This means that the flow of gas ought to rebound quickly. Ukrainian president Zelensky criticized the Canadian decision, saying that it will help Russia.\n Meanwhile, Germany’s government has said it does not accept the Gazprom explanation for the curtailment of gas flows and fears that more trouble is brewing. A German government spokeswoman said, “We don’t see technical reasons. Our information is that this turbine is a replacement turbine that was earmarked for use in September but, again, we are doing everything to take away possible pretexts for the Russia side.” Gazprom has said that the recent disruption of supplies is beyond its control.\n There is a debate as to what Russia might do next, and why. If Russia halts or significantly reduces deliveries of gas to Germany during the winter months, the ostensible reason would be to undermine German determination to maintain sanctions, as well as to undermine German unity with other EU members. However, doing so might damage Russia’s reputation for being a reliable business partner and would likely cause an acceleration in German efforts to reduce dependence on Russia. Thus, the counterargument is that Russia has reduced deliveries as a warning but does not intend to fully upset its relationship with Germany. The well-known strategist Ian Bremmer says that, if Russia didn’t care about its future relations with Germany, it would not create implausible excuses for cutting gas deliveries. Time will tell. In any event, the European Commission says it does not expect gas flows to resume as scheduled and will plan accordingly. ",
  },
  {
    id: 4,
    title:
      "Women in the workplace stay with “gender equality leaders,” survey finds",
    category: "Women",
    img: blog2,
    content:
      "Women in the workplace may feel slightly better about their jobs than they did last year, but that doesn’t necessarily mean that they intend to stay with their employers, Deloitte’s 2022 Women @ Work report suggests.\n More than half of the 5,000 women surveyed across 10 countries said they plan to leave their current employers within two years. Additionally, 10% were currently looking for a new job with another organization—four percentage points more than in 2021. This increase occurred even though respondents were also more likely to report higher levels of job satisfaction, slightly better work/life balance, and higher feelings of loyalty to their employer, compared to those surveyed last year. \n Looking beyond what may seem like contradictory results, a critical takeaway for employers is clear: Organizations that foster a respectful and inclusive culture see higher levels of employee motivation, productivity, and retention. \n Deloitte’s research identified a group of “gender equality leaders,” organizations that, according to the women surveyed, have created genuinely inclusive cultures that support their careers, promote work/life balance, and foster inclusion. Deloitte also identified a group of “lagging” organizations. The women who work for these businesses indicate that their employers have a less inclusive, low-trust culture that doesn’t adequately support their career progression or work/life balance.",
  },
  {
    id: 5,
    title: "A new globalization calculus",
    category: "World",
    img: blog1,
    content:
      "With apologies to Mark Twain, the reports of globalization’s death are greatly exaggerated. Despite recent and seemingly seismic disruptions—a global pandemic, geopolitical hostilities, and whatever comes next—it’s unlikely that most companies will retreat from the world. However, the nature of globalization has changed, and with it, the nature of leaders’ strategic decision-making. \n We asked Deloitte specialists, researchers and economists, and academics at US business schools to assess the future of globalization and ponder what leading in this new era might entail. They told us that today’s unpredictable world requires a new calculus. Rather than making decisions based primarily on cost, efficiency, and speed, executives now have to give more consideration to risk and resilience. Following years of strategic decision-making focused on “just in time” delivery, the aim right now is “just in case” preparedness.\n While world events might have prompted some vacillations over the years, the overall trajectory of globalization has held relatively steady. “Globalization is a big concept that is hard to measure,” says Steven Altman, a professor at New York University’s Stern School of Business and director of its Center for the Future of Management. “People tend to have perceptions of globalization that are pretty far from reality.”1",
  },
  {
    id: 6,
    title: "Who is setting the pace for personal sustainability?",
    category: "Personality",
    img: blog6,
    content:
      "Climate change and other ecological crises are about people. Our families, friends, neighbors, and colleagues will feel the effects. Many already are. People will be at the heart of solving these crises, too. As the costs and impacts of climate change become clearer, so too does the case for systems-level transformations spanning energy, mobility, food, industry, and more.1 However, changes are only possible through collective action, built through cumulative shifts in attitudes and behaviors. \n Because our choices are profoundly shaped by their context—by what our friends, family, colleagues, and communities do—the impact of an individual action can extend beyond the immediate effect, subtly influencing the behaviors of those around us. In fact, research on social movements and change suggests that a relatively small number of dedicated individuals can catalyze much wider and more rapid shifts in the broader environment.\n In the aggregate, such social contagion effects can have dramatic impacts on attitudes and behaviors, as seen on issues such as smoking and marriage equality.3 That’s why personal efforts toward living a more sustainable life matter. It’s less about the individual emissions avoided by walking rather than driving and more about the example the act sets for others. \n So how do we build societal support for a low-carbon transformation? \n We’ve created the Deloitte Sustainable Actions Index to help answer that question. Our goal is to understand what inspires individual and collective action on sustainability-oriented behaviors. This analysis can be applied to understand how close (or not) we might be to societal tipping points in behaviors and identify the levers companies and governments can use to both respond to, and encourage, the broader adoption of pro-climate norms. It is part of an ongoing effort to look at individual sustainability efforts in new ways, centered around how companies, governments, and civil society can catalyze the rapid adoption of more sustainable practices by people. This is the first in what will be a series of studies exploring different applications of these ideas. ",
  },
];
